//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplication
    {
        public Aplication()
        {
            this.AppsToBlocks = new HashSet<AppsToBlock>();
            this.BlockedApps = new HashSet<BlockedApp>();
            this.Windows = new HashSet<Window>();
        }
    
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public string Company { get; set; }
        public int UserID { get; set; }
        public string WinName { get; set; }
    
        public virtual Uzer User { get; set; }
        public virtual ICollection<AppsToBlock> AppsToBlocks { get; set; }
        public virtual ICollection<BlockedApp> BlockedApps { get; set; }
        public virtual ICollection<Window> Windows { get; set; }
    }
}
