//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppsToBlock
    {
        public int AppsToBlockID { get; set; }
        public int UserID { get; set; }
        public int ApplicationID { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public long TimeMin { get; set; }
        public long TimeMax { get; set; }
    
        public virtual Aplication Application { get; set; }
        public virtual Uzer User { get; set; }
    }
}
