//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLog
    {
        public int FileLogID { get; set; }
        public string Path { get; set; }
        public string NewPath { get; set; }
        public string Event { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
    
        public virtual Uzer User { get; set; }
    }
}
