//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screenshot
    {
        public int ScreenshotID { get; set; }
        public System.DateTime Date { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int LogID { get; set; }
        public byte[] Screensht { get; set; }
        public double PopupHeight { get; set; }
        public double PopupWidth { get; set; }
    
        public virtual Log Log { get; set; }
    }
}
