//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingsID { get; set; }
        public bool Licence { get; set; }
        public bool RunAtStartup { get; set; }
        public bool EnableKeylogger { get; set; }
        public bool TakeScreenshots { get; set; }
        public bool Stealth { get; set; }
        public bool EnableFileWatcher { get; set; }
        public bool FileWatcherSubdirectories { get; set; }
        public bool IsMasterPasswordSet { get; set; }
        public bool DeleteOldLogs { get; set; }
        public bool EnableEmailReports { get; set; }
        public bool EmailSSL { get; set; }
        public bool LightTheme { get; set; }
        public bool FirstRun { get; set; }
        public bool LoggingEnabled { get; set; }
        public int EmailSmtpPort { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
        public string EmailSmtpHost { get; set; }
        public string EmailSmtpUsername { get; set; }
        public string EmailSmtpPassword { get; set; }
        public double EmailInterval { get; set; }
        public double TimerInterval { get; set; }
        public string FileWatcherPath { get; set; }
        public short OldLogDeleteDays { get; set; }
        public double MainWindowLeft { get; set; }
        public double MainWindowTop { get; set; }
        public double MainWindowWidth { get; set; }
        public double MainWindowHeight { get; set; }
        public string WindowOpen { get; set; }
        public System.DateTime TrialStartDate { get; set; }
        public bool EnableIdle { get; set; }
        public long IdleTimer { get; set; }
        public double ScreenshotWindowWidth { get; set; }
        public double ScreenshotWindowHeight { get; set; }
        public double ScreenshotWindowTop { get; set; }
        public double ScreenshotWindowLeft { get; set; }
        public Nullable<System.DateTime> LastExecutedDate { get; set; }
        public string Username { get; set; }
    }
}
