//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usage
    {
        public Usage()
        {
            this.Logs = new HashSet<Log>();
            this.SelfUsages = new HashSet<Usage>();
            this.SelfUsage = new HashSet<Usage>();
        }
    
        public int UsageID { get; set; }
        public int UsageTypeID { get; set; }
        public int UserID { get; set; }
        public System.DateTime UsageStart { get; set; }
        public System.DateTime UsageEnd { get; set; }
        public bool IsCurrent { get; set; }
        public Nullable<int> SelfUsageID { get; set; }
    
        public virtual UsageType UsageType { get; set; }
        public virtual Uzer User { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<Usage> SelfUsages { get; set; }
        public virtual ICollection<Usage> SelfUsage { get; set; }
    }
}
