//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public Log()
        {
            this.Screenshots = new HashSet<Screenshot>();
        }
    
        public int LogID { get; set; }
        public int WindowID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Keystrokes { get; set; }
        public string KeystrokesRaw { get; set; }
        public System.DateTime DateEnded { get; set; }
        public int UsageID { get; set; }
    
        public virtual Window Window { get; set; }
        public virtual ICollection<Screenshot> Screenshots { get; set; }
        public virtual Usage Usage { get; set; }
    }
}
