//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Logger_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Window
    {
        public Window()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int WindowID { get; set; }
        public int ApplicationID { get; set; }
        public string Title { get; set; }
    
        public virtual Aplication Application { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
